/**
 * POST /api/process-video
 *
 * Kicks off the AI processing pipeline for a job that the browser
 * already created in Supabase. The server stores status in an in-memory
 * Map — no server↔Supabase network calls needed here.
 *
 * Browser flow:
 *   1. Browser generates jobId (crypto.randomUUID())
 *   2. Browser inserts job row to Supabase directly
 *   3. Browser calls POST /api/process-video with jobId + job details
 *   4. Browser polls GET /api/process-video/status?jobId=... (reads in-memory map)
 *   5. Browser writes final status + result_clips to Supabase when complete
 *
 * GET /api/process-video
 *   Health check — returns { ok: true, env: { supabase: boolean } }
 */

import { NextRequest, NextResponse } from "next/server";
import { processVideo, jobStatusMap, ProcessingJob } from "@/lib/videoProcessor";
import { isValidYouTubeUrl } from "@/lib/youtubeUtils";

export const runtime = "nodejs";

// ── In-memory rate limiting (3 submissions per hour per IP) ──────────────────
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();
const RATE_LIMIT_MAX = 3;
const RATE_LIMIT_WINDOW_MS = 60 * 60 * 1000;

function checkRateLimit(ip: string): { allowed: boolean; resetIn: string } {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return { allowed: true, resetIn: "60 minutes" };
  }
  if (entry.count >= RATE_LIMIT_MAX) {
    const minutesLeft = Math.ceil((entry.resetAt - now) / 60000);
    return { allowed: false, resetIn: `${minutesLeft} minute${minutesLeft !== 1 ? "s" : ""}` };
  }
  entry.count += 1;
  return { allowed: true, resetIn: "60 minutes" };
}

function getClientIp(request: NextRequest): string {
  return (
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    request.headers.get("x-real-ip") ??
    "unknown"
  );
}

// ── GET — health check ────────────────────────────────────────────────────────
export async function GET() {
  const supabaseConfigured =
    !!process.env.NEXT_PUBLIC_SUPABASE_URL &&
    !!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY !== "your-anon-key-here";

  return NextResponse.json({
    ok: true,
    timestamp: new Date().toISOString(),
    env: { supabase: supabaseConfigured, resend: !!process.env.RESEND_API_KEY },
  });
}

// ── POST — start processing ───────────────────────────────────────────────────
export async function POST(request: NextRequest) {
  const ip = getClientIp(request);
  const rateCheck = checkRateLimit(ip);
  if (!rateCheck.allowed) {
    return NextResponse.json(
      { error: `Too many requests. Please wait ${rateCheck.resetIn} before submitting another video.`, rateLimited: true },
      { status: 429 }
    );
  }

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const {
    jobId,
    videoUrl,
    firstName,
    lastName,
    jerseyNumber,
    jerseyColor,
    position,
    sport,
    school,
    email,
    queuePosition,
  } = body as {
    jobId?: string;
    videoUrl?: string;
    firstName?: string;
    lastName?: string;
    jerseyNumber?: number | string;
    jerseyColor?: string;
    position?: string;
    sport?: string;
    school?: string;
    email?: string;
    queuePosition?: number;
  };

  // jobId must be browser-generated UUID
  if (!jobId?.trim()) {
    return NextResponse.json({ error: "Missing jobId — must be generated by the browser" }, { status: 400 });
  }

  const missing: string[] = [];
  if (!videoUrl?.trim())  missing.push("videoUrl");
  if (!firstName?.trim()) missing.push("firstName");
  if (!lastName?.trim())  missing.push("lastName");
  if (jerseyNumber === undefined || jerseyNumber === null || jerseyNumber === "") missing.push("jerseyNumber");
  if (!position?.trim())  missing.push("position");
  if (!sport?.trim())     missing.push("sport");
  if (!school?.trim())    missing.push("school");
  if (!email?.trim())     missing.push("email");

  if (missing.length > 0) {
    return NextResponse.json({ error: `Missing required fields: ${missing.join(", ")}` }, { status: 400 });
  }

  const jerseyNum = Number(jerseyNumber);
  if (!Number.isInteger(jerseyNum) || jerseyNum < 0 || jerseyNum > 99) {
    return NextResponse.json({ error: "jerseyNumber must be an integer between 0 and 99" }, { status: 400 });
  }

  const urlStr = videoUrl!.trim();
  const source = isValidYouTubeUrl(urlStr) ? "youtube" : "upload";

  // Initialise status in the in-memory map
  jobStatusMap.set(jobId, { status: "queued", queuePosition: Number(queuePosition) || 1 });

  const job: ProcessingJob = {
    id:           jobId,
    firstName:    firstName!.trim(),
    lastName:     lastName!.trim(),
    jerseyNumber: jerseyNum,
    jerseyColor:  jerseyColor?.trim() || "#FFFFFF",
    position:     position!.trim(),
    sport:        sport!.trim(),
    school:       school!.trim(),
    videoUrl:     urlStr,
    source:       source as "youtube" | "upload",
    email:        email!.trim(),
    status:       "queued",
  };

  console.log(`[process-video] Starting job ${jobId} for ${firstName} ${lastName} #${jerseyNum}`);

  // Fire-and-forget — response returns immediately, client polls /api/process-video/status
  processVideo(job).catch((err) => {
    console.error(`[process-video] Unhandled error in job ${jobId}:`, err);
    jobStatusMap.set(jobId, { status: "failed", errorMessage: String(err) });
  });

  return NextResponse.json({ jobId, status: "queued", queuePosition: Number(queuePosition) || 1 }, { status: 201 });
}
